packages:
  - 'servers/**/*'
  - 'packages/**/*'
overrides:
  '@types/node': '^22.15.30'
  'typescript': '^5.8.3'

  '@modelcontextprotocol/sdk': '^1.12.1'
  'tsc-alias': '^1.8.16'
  'zod': '^3.25.56'
